version: '3'
services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    hostname: nginx
    networks:
      - toynet
    ports:
      - 80:80
      - 443:443

  toychest:
    build:
      context: toychest
    container_name: toychest
    hostname: toychest
    networks:
      - toynet
      - toysupport

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # todo: redesign paramter passing with CI
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - toysupport
    container_name: redis
    hostname: redis
    volumes:
      - 'redis_data:/bitnami/redis/data'

  toydiscover:
    build:
      context: toydiscover
    container_name: toydiscover
    hostname: toydiscover
    networks:
      - toysupport


volumes:
  redis_data:
    driver: local

networks:
  toysupport:
  toynet:
    external:
      name: toynet