version: '3'
services:
  nginx:
    build:
      context: nginx
    image: toychest-nginx:1.0.0
    container_name: nginx
    hostname: nginx
    networks:
      - toynet
    ports:
      - "80:80"
      - "443:443"

  toydb:
    image: mongo  # latest  # todo why do I need a database here? I don't use it O-o
    restart: always
    container_name: toydb
    hostname: toydb
    networks:
      - toysupport
    volumes:
      - database_config:/data/configdb
      - database_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty # todo env variables

  toydiscover:
    build:
      context: toydiscover
    image: toydiscover:1.0.0
    container_name: toydiscover
    depends_on:
      - toydb
      - nginx
    hostname: toydiscover
    environment:
      - DRIVE_INIT_TOKEN=${DRIVE_INIT_TOKEN}
    networks:
      toysupport:
#        aliases:   # example for subdomains
#          - extra.toydiscover

  toychest:
    build:
      context: toychest
    image: toychest:1.0.0
    container_name: toychest
    depends_on:
      - toydiscover
    hostname: toychest
    networks:
      - toysupport
      - toynet

# todo logging monitoring module

volumes:
  database_config:
    driver: local
  database_volume:
    driver: local
  log_volume:
    driver: local

networks:
  toysupport:
  toynet:
    external:
      name: toynet